# Spring Configuration
spring:
  application:
    name: Broker Adapter

# Spring Logging Configuration
logging:
  level:
    es.in2.brokeradapter: DEBUG

# Spring Management Configuration - Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true

# SpringDoc Configuration - OpenAPI 3.0 Documentation & Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Spring Server Configuration
server:
  port: 8080

# Application Configuration
openapi:
  server:
    url:
    description:
  info:
    title:
    version:
    description:
    termsOfService:
    license:
      name:
      url:
    contact:
      email:
      name:
      url:

app:
  contextEnabled: true

# Context Broker Configuration
broker:
  externalDomain:
  internalDomain:
  paths:
    entities:
    subscriptions:
