# Spring Configuration
spring:
  application:
    name: Orion-LD Interface
  config:
    import:
      - classpath:custom-config.yml
      - file:/src/main/resources/custom-config.yml

# Spring Server Configuration
server:
  port: 8080

# Spring Logging Configuration
logging:
  level:
    es.in2.orionld: DEBUG

# Spring Management Configuration - Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true

# SpringDoc Configuration - OpenAPI 3.0 Documentation & Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Application Configuration
app:
  openapi:
    dev-url: http://localhost:8080