# Context Broker Configuration
broker:
  externalDomain: https://<domain.org>/orion-ld
  internalDomain: http://localhost:1026

# Broker Adapter Configuration
broker-adapter:
  openapi:
    url: http://localhost:8080