version: '3'
services:

  #Zookeeper
  zookeeper:
    image: zookeeper
    ports:
      - "2181"

  #Kafka
  kafka:
    image: bitnami/kafka:3.5.1-debian-11-r6
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  #Postgres
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  #Scorpio
  scorpio:
    image: scorpiobroker/all-in-one-runner:java-kafka-4.1.10
#    image: scorpiobroker/all-in-one-runner:java-kafka-4.1.10 # used in DOME
    ports:
      - "9090:9090"
    environment:
      DBHOST: postgres
      BUSHOST: kafka
    depends_on:
      - postgres
      - kafka

volumes:
  postgres-data:

# docker-compose -f docker-compose-scorpio-aio.yml up -d