version: "3.8"
services:

  # Orion I/F
  blockchain-connector-orionld-interface:
    container_name: blockchain-connector-orionld-interface
    image: blockchain-connector-orionld-interface
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8280:8280"
    networks:
      - local_net

  # Orion I/F
  blockchain-connector-orionld-interface-2:
    container_name: blockchain-connector-orionld-interface-2
    image: blockchain-connector-orionld-interface
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8281:8281"
    networks:
      - local_net

  # Context Broker
  context-broker-2:
    container_name: context-broker-2
    image: fiware/orion-ld:latest
    command: "-dbhost context-broker-mongo-2"
    ports:
      - "1027:1026"
    links:
      - context-broker-mongo-2
    networks:
      - local_net

  # Context Broker MongoDB
  context-broker-mongo-2:
    container_name: context-broker-mongo-2
    image: mongo:4.4
    command: "--nojournal"
    volumes:
      - CONTEXT_BROKER_1:/data/db
      - CONTEXT_BROKER_DBCONFIG_1:/data/configdb
    networks:
      - local_net

  # Context Broker
  context-broker:
    container_name: context-broker
    image: fiware/orion-ld:latest
    command: "-dbhost context-broker-mongo"
    expose:
      - "1026"
    ports:
      - "1026:1026"
    links:
      - context-broker-mongo
    networks:
      - local_net

  # Context Broker MongoDB
  context-broker-mongo:
    container_name: context-broker-mongo
    image: mongo:4.4
    command: "--nojournal"
    volumes:
      - CONTEXT_BROKER:/data/db
      - CONTEXT_BROKER_DBCONFIG:/data/configdb
    networks:
      - local_net

networks:
  local_net:
volumes:
  CONTEXT_BROKER:
  CONTEXT_BROKER_DBCONFIG:
  CONTEXT_BROKER_1:
  CONTEXT_BROKER_DBCONFIG_1:

